// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxw0CHyq5WBiV4Y0FojFJH0obsmvzvq8',
    appId: '1:277868174291:web:06c0d64286c2e8ef2e2d26',
    messagingSenderId: '277868174291',
    projectId: 'basictest-67763',
    authDomain: 'basictest-67763.firebaseapp.com',
    databaseURL: 'https://basictest-67763-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-67763.firebasestorage.app',
    measurementId: 'G-SZY5SRG07Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJTiuky8xqNvK1dqYDFA_o5BTU1cYa0w',
    appId: '1:277868174291:android:80016efebf84e9d72e2d26',
    messagingSenderId: '277868174291',
    projectId: 'basictest-67763',
    databaseURL: 'https://basictest-67763-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-67763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayCrPsxLajQItmV1rJTsh0UqocsfQPd4',
    appId: '1:277868174291:ios:db5d84aa86ccab692e2d26',
    messagingSenderId: '277868174291',
    projectId: 'basictest-67763',
    databaseURL: 'https://basictest-67763-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-67763.firebasestorage.app',
    androidClientId: '277868174291-1d0atinenc20ijvb2n8of2v80gpb30qe.apps.googleusercontent.com',
    iosClientId: '277868174291-uvnvsq6ofcrm84r0jfhr9ek3t3ob5bcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.weintalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCayCrPsxLajQItmV1rJTsh0UqocsfQPd4',
    appId: '1:277868174291:ios:db5d84aa86ccab692e2d26',
    messagingSenderId: '277868174291',
    projectId: 'basictest-67763',
    databaseURL: 'https://basictest-67763-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-67763.firebasestorage.app',
    androidClientId: '277868174291-1d0atinenc20ijvb2n8of2v80gpb30qe.apps.googleusercontent.com',
    iosClientId: '277868174291-uvnvsq6ofcrm84r0jfhr9ek3t3ob5bcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.weintalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfxw0CHyq5WBiV4Y0FojFJH0obsmvzvq8',
    appId: '1:277868174291:web:a6e6bc1302eab6ac2e2d26',
    messagingSenderId: '277868174291',
    projectId: 'basictest-67763',
    authDomain: 'basictest-67763.firebaseapp.com',
    databaseURL: 'https://basictest-67763-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-67763.firebasestorage.app',
    measurementId: 'G-EXN9H95X50',
  );
}
